In [ ]:
p,q,n = 6,7,9
print (p)
print (q)
print(n)

6
7
9


In [ ]:
x=y=z=12
print (x)
print (y)
print (z)

12
12
12


In [ ]:
s, t, r = "big", "ball", "throw"
My_var= s+t
print (My_var)

bigball


In [ ]:
x=1 #integer
y=8.99 #float
z=8j #complex number
print (type(x))
print (type(z))

<class 'int'>
<class 'complex'>


In [ ]:
u=6
p=float(u)
print(u)

6


In [ ]:
q=complex(y)
q=complex(y)
print(q)

(8.99+0j)


In [ ]:
#create an array using python
my_array=[1,2,3,4,5,6,7,8]
print(my_array)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
celsius = float(50)
print(f"{celsius}°C is equal to {fahrenheit}°F")


50.0°C is equal to 35.6°F


In [ ]:
from typing import Final
a1=[1,3,5,4,6,7]
a2=[3,5,9,1,0,5]
b=a1+a2
print(b)

[1, 3, 5, 4, 6, 7, 3, 5, 9, 1, 0, 5]


In [ ]:
x,y=2,5
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)  #modulus
print(x**y) #exponential

7
-3
10
0.4
2
32


In [ ]:
s=34
s+=11

print (s)
s-=30
print (s)

45
15


In [ ]:
#matrix operation
import numpy as np
array1= np.array([[1,2,4,2,5], [4,7,9,6,1]]) #array must be put
print(array1)

[[1 2 4 2 5]
 [4 7 9 6 1]]


In [ ]:
array1 [0,2] #1st row x 3rd cloumn (starts with 0)


4

In [ ]:
array1 [1,2]

9

In [ ]:
array1[1,4]

1

In [ ]:
#matrix operation
p=np.array([[1,2,3],[4,5,6]])
q=np.array([[2,7,6],[1,2,5]])
print(p)
print(q)


[[1 2 3]
 [4 5 6]]
[[2 7 6]
 [1 2 5]]


In [ ]:
p=np.array([[1,2,3],[4,5,6]]) #matrix addition
q=np.array([[2,7,6],[1,2,5]])
print(p)
print(q)
print(np.add(p,q))

[[1 2 3]
 [4 5 6]]
[[2 7 6]
 [1 2 5]]
[[ 3  9  9]
 [ 5  7 11]]


In [ ]:
p=np.array([[1,2,3],[4,5,6]]) #matrix subtract
q=np.array([[2,7,6],[1,2,5]])
print(p)
print(q)
print(np.subtract(p,q))

[[1 2 3]
 [4 5 6]]
[[2 7 6]
 [1 2 5]]
[[-1 -5 -3]
 [ 3  3  1]]


In [ ]:
p=np.array([[1,2,3],[4,5,6]]) #matrix multiply
q=np.array([[2,7,6],[1,2,5]])
print(p)
print(q)
print(np.multiply(p,q))

[[1 2 3]
 [4 5 6]]
[[2 7 6]
 [1 2 5]]
[[ 2 14 18]
 [ 4 10 30]]


In [ ]:
p=np.array([[1,2,3],[4,5,6]]) #matrix divison
q=np.array([[2,7,6],[1,2,5]])
print(p)
print(q)
print(np.divide(p,q))

[[1 2 3]
 [4 5 6]]
[[2 7 6]
 [1 2 5]]
[[0.5        0.28571429 0.5       ]
 [4.         2.5        1.2       ]]


In [ ]:
celsius= 97.2
fahrenheit= (celsius * 1.8)+ 32
print(f"{celsius}° celsius is equal to {fahrenheit}° fahrenheit")

97.2° celsius is equal to 206.96° fahrenheit
